### ISSUE TITLE
Issue + New Feature Request

### ISSUE THREAD

**Issue by Apothocary** [eriknyk/youtb#2]
Hi Erik,

I continue to use your app, but I've run into an issue.

Using the YouTube volume slider is impossible. Clicking and dragging just seems to move the whole window around instead. Same thing happens if I click-drag to highlight text in the search box up top.

New feature request: a back button (also with Touchpad gestures, like two finger swipe).

Thanks!

**Comment by eriknyk** [comment]
I will check both, thanks @Apothocary

**Comment by Apothocary** [comment]
Thanks! Look forward to any and all updates!

**Comment by eriknyk** [comment]
hey buddy @Apothocary, in what OS are you using the app? macOS?
to fix these issues and release the fixed version for the platform that you using.

**Comment by Apothocary** [comment]
Mac OS Big Sur!

**Comment by eriknyk** [comment]
@Apothocary  both issue fixed + feature(back button) are done!, 
a new zip package was upload (only for MacOS, package for other platforms pending)

v1.0.1 https://github.com/eriknyk/youtb/releases/tag/1.0.1

Regards.

<img width="1264" alt="Screen Shot 2021-02-02 at 21 08 41" src="https://user-images.githubusercontent.com/205721/106688135-89baf780-659b-11eb-80da-5e508dbd11b8.png">

**Comment by Apothocary** [comment]
Thanks Erik! The volume slider and back button work great.

The search bar still suffers from the same issue though, unfortunately. If you try highlight text you'll see what I mean.

Now just for the tabs and this will be my favorite new app ;)

Great work.

**Comment by eriknyk** [comment]
Hey buddy @Apothocary I just fixed the issue in search bar, you can find the fixed version in the latest build (1.0.2 - https://github.com/eriknyk/youtb/releases/tag/1.0.2)

Thanks for your contribution, best regards!
